name: Node.js CI

on:
  push:
    branches:
      - canary
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build
    - name: Build storybook
      run: npm run build-storybook
    - name: Install Chromium
      run: npx playwright install chromium --with-deps
    - name: Test
      run: |
        npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "node .storybook/serve.js" \
          "npx wait-on tcp:6006 && npx test-storybook"
